name: Renew on Electron

on:
  # schedule:
  #   - cron: "0 8 20 * *" # At 08:00 on day-of-month 20. Reference: https://crontab.guru/

  workflow_dispatch:
    inputs:
      specPath:
        description: Spec files that can run.
        required: true
        type: choice
        default: "cypress/e2e/scenarios/hostname/renew/renew.feature"
        options:
          - cypress/e2e/scenarios/hostname/renew/renew.feature
      user:
        description: Username
        required: true
        type: string
      pass:
        description: Password
        required: true
        type: string

jobs:
  cypress-run:
    name: Renew NoIP Hostname on Electron
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        continue-on-error: true
        with:
          headed: true
          spec: ${{inputs.specPath}}
        env:
          CYPRESS_USER: ${{inputs.user}}
          CYPRESS_PASS: ${{inputs.pass}}
